driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
  - name: ubuntu-13.04
  - name: ubuntu-12.04
  - name: ubuntu-10.04
  - name: debian-7.1.0

suites:
  - name: ufw
    run_list:
      - recipe[firewall::ufw]
      - recipe[ufw-test::default]
  - name: iptables
    run_list:
      - recipe[firewall::iptables]
      - recipe[iptables-test::default]
