driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-12.04
  - name: debian-7.8
  - name: centos-70
    driver_config:
      box: chef/centos-7.0
  - name: centos-66
    driver_config:
      box: chef/centos-6.6

suites:
  - name: default
    run_list:
      - recipe[apt]
      - recipe[firewall::default]
      - recipe[firewall-test::default]
    attributes:
      firewall:
        allow_ssh: true
