driver:
  name: vagrant

provisioner:
  name: chef_zero
  attributes:
    firewall:
      allow_ssh: true
      allow_winrm: true
      firewalld:
        permanent: true

platforms:
  - name: centos-5.11
  - name: centos-6.7
  - name: centos-7.1
  - name: debian-7.8
    run_list:
      - recipe[apt]
  - name: debian-8.1
    run_list:
      - recipe[apt]
  - name: ubuntu-12.04
    run_list:
      - recipe[apt::default]
  - name: ubuntu-14.04
    run_list:
      - recipe[apt::default]
  - name: windows-2012r2
    driver_config:
      box: windows2012r2

suites:
  - name: default
    excludes:
      - windows-2012r2
    run_list:
      - recipe[firewall::default]
      - recipe[firewall-test::default]

  - name: iptables
    excludes:
      - centos-5.11
      - centos-6.7
      - debian-7.8
      - debian-8.1
      - windows-2012r2
    run_list:
      - recipe[firewall-test::default]
    attributes:
      firewall:
        ubuntu_iptables: true
        redhat7_iptables: true
  - name: windows
    excludes:
      - centos-5.11
      - centos-6.7
      - centos-7.1
      - debian-7.8
      - debian-8.1
      - ubuntu-12.04
      - ubuntu-14.04
    run_list:
      - recipe[firewall::default]
      - recipe[firewall-test::windows]
    attributes:
      firewall:
        windows:
          default_rules: false
