---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: true # we should test with both 11.18.12 and latest 12.x
  attributes:
    firewall:
      allow_ssh: true
      allow_winrm: true

platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]
  - name: debian-7.8
    run_list:
      - recipe[apt]
  - name: centos-5.11
  - name: centos-6.6
  - name: centos-7.0
  - name: windows-2012r2

suites:
  - name: default
    run_list:
      - recipe[firewall::default]
      - recipe[firewall-test::default]

  - name: iptables
    excludes:
      - centos-5.11
      - centos-6.6
      - centos-7.0
      - debian-7.8
      - windows-2012r2
    run_list:
      - recipe[firewall-test::default]
    attributes:
      firewall:
        ubuntu_iptables: true
