name: ci

"on":
  pull_request:
  push:
    branches: [main]

jobs:
  lint-unit:
    uses: sous-chefs/.github/.github/workflows/lint-unit.yml@3.1.1
    permissions:
      actions: write
      checks: write
      pull-requests: write
      statuses: write
      issues: write

  firewalld:
    needs: lint-unit
    runs-on: macos-latest
    strategy:
      matrix:
        os:
          - amazonlinux-2
          - centos-7
          - debian-11
          - debian-12
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install VirtualBox
        run: |
          brew update
          brew upgrade virtualbox
      - name: Install Chef
        uses: actionshub/chef-install@3.0.1
      - name: Kitchen Converge
        uses: actionshub/test-kitchen@2.1.0
        with:
          suite: firewalld
          os: ${{ matrix.os }}

  iptables:
    needs: lint-unit
    runs-on: macos-latest
    strategy:
      matrix:
        os:
          - amazonlinux-2
          - centos-7
          - centos-stream-8
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install VirtualBox
        run: |
          brew update
          brew upgrade virtualbox
      - name: Install Chef
        uses: actionshub/chef-install@3.0.1
      - name: Kitchen Converge
        uses: actionshub/test-kitchen@2.1.0
        with:
          suite: iptables
          os: ${{ matrix.os }}

  ufw:
    needs: lint-unit
    runs-on: macos-latest
    strategy:
      matrix:
        os:
          - ubuntu-2004
          - ubuntu-2204
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Chef
        uses: actionshub/chef-install@3.0.1
      - name: Install VirtualBox
        run: |
          brew update
          brew upgrade virtualbox
      - name: Kitchen Converge
        uses: actionshub/test-kitchen@2.1.0
        env:
          CHEF_LICENSE: accept-no-persist
          KITCHEN_LOCAL_YAML: kitchen.dokken.yml
        with:
          suite: ufw
          os: ${{ matrix.os }}

  nftables:
    needs: lint-unit
    runs-on: macos-latest
    strategy:
      matrix:
        os:
          - debian-11
          - debian-12
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Chef
        uses: actionshub/chef-install@3.0.1
      - name: Install VirtualBox
        run: |
          brew update
          brew upgrade virtualbox
      - name: Kitchen Converge
        uses: actionshub/test-kitchen@2.1.0
        with:
          suite: nftables
          os: ${{ matrix.os }}

  firewalld-dbus:
    needs: lint-unit
    runs-on: macos-latest
    strategy:
      matrix:
        os:
          - debian-11
          - debian-12
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Chef
        uses: actionshub/chef-install@3.0.1
      - name: Install VirtualBox
        run: |
          brew update
          brew upgrade virtualbox
      - name: Kitchen Converge
        uses: actionshub/test-kitchen@2.1.0
        with:
          suite: firewalld-dbus
          os: ${{ matrix.os }}

  verify:
    needs: [firewalld, iptables, ufw, nftables, firewalld-dbus]
    runs-on: ubuntu-latest
    steps:
      - name: Success
        run: echo "All test suites completed successfully!"
