name: ci

'on':
  pull_request:
  push:
    branches: [main]

jobs:
  lint-unit:
    uses: sous-chefs/.github/.github/workflows/lint-unit.yml@0.0.3
    permissions:
      actions: write
      checks: write
      pull-requests: write
      statuses: write
      issues: write

  integration:
    needs: lint-unit
    runs-on: macos-10.15
    strategy:
      matrix:
        os:
          - amazonlinux-2
          - debian-9
          - debian-10
          - centos-7
          - centos-stream-8
          - ubuntu-1804
          - ubuntu-2004
        suite:
          - firewalld
          - iptables
          - ufw
        exclude:
          - os: amazonlinux-2
            suite: ufw
          - os: debian-9
            suite: firewalld
          - os: debian-9
            suite: iptables
          - os: debian-10
            suite: firewalld
          - os: debian-10
            suite: iptables
          - os: centos-7
            suite: ufw
          - os: centos-stream-8
            suite: ufw
          - os: centos-stream-8
            suite: firewalld
          - os: ubuntu-1804
            suite: firewalld
          - os: ubuntu-1804
            suite: iptables
          - os: ubuntu-2004
            suite: firewalld
          - os: ubuntu-2004
            suite: iptables
      fail-fast: false
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install Chef
        uses: actionshub/chef-install@main
      - name: kitchen
        uses: actionshub/test-kitchen@main
        env:
          CHEF_LICENSE: accept-no-persist
        with:
          suite: ${{ matrix.suite }}
          os: ${{ matrix.os }}
